model:
  embedding:
    provider: "huggingface"    # Options: openai | huggingface | bedrock | stub
    model_id: "sentence-transformers/all-MiniLM-L6-v2"
    dim: 384

  image_encoder: "openai/clip-vit-base-patch32"

  llm:
    provider: "openai"         # Options: openai | huggingface | bedrock | stub
    model_id: "gpt-4"
    temperature: 0.3
    max_tokens: 512

retriever:
  top_k: 5
  similarity_metric: "l2"

data:
  input_dir: "data/input"
  output_dir: "data/output"
  persist_dir: "data/index"

vectorstore:
  type: "faiss"
  index_path: "data/index/faiss.index"
  metadata_path: "data/index/metadata.json"

pipeline:
  chunk_size: 500
  chunk_overlap: 50
  use_page_images: true
  use_tables: true
  use_text: true
  use_images: true
