# ---------------------------------------------------------
# Author: GHNAMI Helmi
# Date: 2025-09-26
# Position: Data-Science
# ---------------------------------------------------------
name: CI/CD - All Projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [langchain, multimodal-rag-pipeline, rag-qa-bot-langchain]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: pytest -q

  docker-multimodal:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker build -t ghcr.io/helmighanmi/generative-ai-applications/multimodal-rag-pipeline:latest -f multimodal-rag-pipeline/Dockerfile multimodal-rag-pipeline
      - run: docker push ghcr.io/helmighanmi/generative-ai-applications/multimodal-rag-pipeline:latest
